name: D

on: [ push, pull_request ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1

    - name: 'Build & Test'
      shell: cmd
      run: |
        rem Build the project, with its main file included, without unittests
        dub build -b release --compiler=%DC%
        rem Build and run tests, as defined by `unittest` configuration
        rem In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        rem See https://dub.pm/package-format-json.html#configurations
        rem dub test --compiler=$DC  # package not ready for this yet
        
